[package]
name = "symbolica-typst-plugin"
version = "0.1.0"
edition = "2024"
license-file = "../../License.md"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
symbolica = { path = "../..", default-features = false, features = ["no_gmp", "typst_plugin"] }
wasm-minimal-protocol = "0.1.0"
getrandom = "0.3.4"
ciborium = "0.2.2"
